version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: "@sudoo/triforce"
    versions:
    - 2.9.16
    - 2.9.17
    - 2.9.18
    - 2.9.20
    - 2.9.21
    - 2.9.22
  - dependency-name: axios
    versions:
    - 0.21.1
